In [3]:
import os
os.listdir()

['.anaconda',
 '.bash_history',
 '.cache',
 '.codex',
 '.conda',
 '.continuum',
 '.copilot',
 '.DbSchema',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.local',
 '.matplotlib',
 '.ms-ad',
 '.python_history',
 '.venv',
 '.viminfo',
 '.virtual_documents',
 '.vscode',
 '.vscode-shared',
 '3D Objects',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'file1.txt',
 'home-credit-default-risk (2).zip',
 'IntelGraphicsProfiles',
 'Ironhack',
 'lab-sql-mysql-db-creation',
 'Links',
 'Local Settings',
 'miniconda3',
 'Music',
 'My Documents',
 'mynewfile',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{5dd224dd-18c0-11ea-a26a-c85b76c3130e}.TM.blf',
 'NTUSER.DAT{5dd224dd-18c0-11ea-a26a-c85b76c3130e}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{5dd224dd-18c0-11ea-a26a-c85b76c3130e}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'untitled.py',
 'Untitled1.ipynb',
 'Videos']

In [6]:
import zipfile

with zipfile.ZipFile("home-credit-default-risk (2).zip", "r") as zip_file:
    zip_file.extractall("home_credit_data")

In [7]:
os.listdir("home_credit_data")

['application_test.csv',
 'application_train.csv',
 'bureau.csv',
 'bureau_balance.csv',
 'credit_card_balance.csv',
 'HomeCredit_columns_description.csv',
 'installments_payments.csv',
 'POS_CASH_balance.csv',
 'previous_application.csv',
 'sample_submission.csv']

In [9]:
import pandas as pd

df = pd.read_csv("home_credit_data/application_train.csv")

In [10]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df.shape

(307511, 122)

In [16]:
bureau_df = pd.read_csv(
    "home_credit_data/bureau.csv"
)

In [14]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
df.shape

(307511, 122)

In [18]:
application_columns = [
    # Connecting key
    "SK_ID_CURR",

    # Default outcome
    "TARGET",

    # Applicant profile
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_INCOME_TYPE",
    "OCCUPATION_TYPE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "NAME_CONTRACT_TYPE"
]

In [19]:
missing_columns = [
    column for column in application_columns
    if column not in df.columns
]

missing_columns

[]

In [20]:
application_trimmed_df = df[
    application_columns
].copy()

In [21]:
application_trimmed_df.head()

,SK_ID_CURR,TARGET,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_INCOME_TYPE,OCCUPATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,NAME_CONTRACT_TYPE
0,100002,1,Secondary / secondary special,Single / not married,Working,Laborers,-9461,-637,Cash loans
1,100003,0,Higher education,Married,State servant,Core staff,-16765,-1188,Cash loans
2,100004,0,Secondary / secondary special,Single / not married,Working,Laborers,-19046,-225,Revolving loans
3,100006,0,Secondary / secondary special,Civil marriage,Working,Laborers,-19005,-3039,Cash loans
4,100007,0,Secondary / secondary special,Single / not married,Working,Core staff,-19932,-3038,Cash loans

In [22]:
application_trimmed_df.shape

(307511, 9)

In [23]:
application_trimmed_df.to_csv(
    "application_trimmed.csv",
    index=False
)

In [25]:
bureau_df.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [26]:
bureau_df.shape

(1716428, 17)

In [29]:
import pandas as pd

In [31]:
bureau_df.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [38]:
bureau_columns = [
    "SK_ID_CURR",
    "SK_ID_BUREAU", "CREDIT_DAY_OVERDUE"
]

In [39]:
bureau_trimmed_df = bureau_df[
    bureau_columns
].copy()

In [40]:
bureau_trimmed_df.head()

   SK_ID_CURR  SK_ID_BUREAU  CREDIT_DAY_OVERDUE
0      215354       5714462                   0
1      215354       5714463                   0
2      215354       5714464                   0
3      215354       5714465                   0
4      215354       5714466                   0

In [41]:
bureau_trimmed_df.to_csv(
    "bureau_trimmed.csv",
    index=False
)

In [44]:
import pandas as pd

previous_df = pd.read_csv("home_credit_data/previous_application.csv")

In [46]:
previous_df.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
previous_columns = [
    "SK_ID_CURR",
    "SK_ID_PREV",
    "NAME_CONTRACT_STATUS",
    "CODE_REJECT_REASON",
    "DAYS_DECISION",
    "NAME_PORTFOLIO",
    "NAME_YIELD_GROUP",
    "CHANNEL_TYPE",
    "NAME_SELLER_INDUSTRY"
]

previous_trimmed_df = previous_df[previous_columns].copy()

In [48]:
previous_trimmed_df.head()

,SK_ID_CURR,SK_ID_PREV,NAME_CONTRACT_STATUS,CODE_REJECT_REASON,DAYS_DECISION,NAME_PORTFOLIO,NAME_YIELD_GROUP,CHANNEL_TYPE,NAME_SELLER_INDUSTRY
0,271877,2030495,Approved,XAP,-73,POS,middle,Country-wide,Connectivity
1,108129,2802425,Approved,XAP,-164,Cash,low_action,Contact center,XNA
2,122040,2523466,Approved,XAP,-301,Cash,high,Credit and cash offices,XNA
3,176158,2819243,Approved,XAP,-512,Cash,middle,Credit and cash offices,XNA
4,202054,1784265,Refused,HC,-781,Cash,high,Credit and cash offices,XNA

In [50]:
previous_trimmed_df.shape

(1670214, 9)

In [51]:
previous_trimmed_df.to_csv(
    "previous_application_trimmed.csv",
    index=False
)